version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
  exclusions:
    paths:
      - vendor
      - testdata
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - noctx
      - path: _templ\.go$
        linters:
          - all
      - path: web/
        text: "build constraints exclude all Go files"

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
