version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
  exclusions:
    paths:
      - vendor
      - testdata
      - ".*_templ\\.go$"
      - "^\\.dagger/.*"
    rules:
      - path: "^\\.dagger"
        linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
          - misspell
          - unconvert
          - bodyclose
          - noctx
          - errorlint
          - typecheck
      - path: _test\.go
        linters:
          - errcheck
          - noctx
      - path: web/
        text: "build constraints exclude all Go files"

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
