version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - noctx
    - path: _templ\.go$
      linters:
        - all
    - path: web/
      text: "build constraints exclude all Go files"
  exclude-dirs:
    - vendor
    - testdata
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
