version: "2"

run:
  timeout: 5m
  skip-dirs:
    - .dagger
  skip-files:
    - ".dagger/.*"
  modules-download-mode: readonly
  allow-parallel-runners: true
  exclude-dirs:
    - .dagger

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*_templ\\.go$"
    - "^\\.dagger/.*"
  exclude-rules:
    - path: "^\\.dagger"
      linters:
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unused
        - misspell
        - unconvert
        - bodyclose
        - noctx
        - errorlint
        - typecheck
    - path: _test\.go
      linters:
        - errcheck
        - noctx
    - path: web/
      text: "build constraints exclude all Go files"
