version: '3'

vars:
  APP_NAME: readwillbe
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  IMAGES:
    - dev
  DEV_IMAGE: '{{.APP_NAME}}:dev'

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds:
      - task --list

  docker:build-target:
    internal: true
    cmds:
      - docker build --target {{.DOCKER_TARGET}} -t {{.DOCKER_IMAGE}} --build-arg APP_NAME={{.APP_NAME}} --build-arg VERSION={{.GIT_COMMIT}} .

  docker:clean-image:
    internal: true
    cmds:
      - docker rmi {{.DOCKER_IMAGE}}
    silent: true
    ignore_error: true

  docker:clean-images:
    internal: true
    cmds:
      - for: { var: IMAGES }
        task: docker:clean-image
        vars: { DOCKER_IMAGE: '{{.APP_NAME}}:{{.ITEM}}' }

  clean:bun:
    internal: true
    desc: Clean bun leftovers
    cmds:
      - rm -rf node_modules
      - rm bun.lock

  clean:
    desc: Remove generated files and Docker images
    deps: [clean:bun]
    cmds:
      - rm -rf ./tmp ./bin
    silent: true
    ignore_error: true

  build-dev:
    internal: true
    desc: Build development Docker image
    cmds:
      - task: docker:build-target
        vars:
          DOCKER_TARGET: dev
          DOCKER_IMAGE: '{{.DEV_IMAGE}}'

  dev:
    desc: Start development environment with hot reload
    deps: [build-dev]
    cmds:
      - defer:
          echo '{{if eq .EXIT_CODE 2}}Docker stopped.{{else}}Exited with - {{.EXIT_CODE}}{{end}}'
      - defer: { task: clean }
      - docker run --rm
        --name {{.APP_NAME}}-dev
        -p 8080:8080 -p 7331:7331
        -v {{.ROOT_DIR}}:/app
        -v go-mod-cache:/go/pkg/mod
        -v go-build-cache:/go-build-cache
        -e READWILLBE_PORT=:8080
        -e READWILLBE_DB_PATH=/app/data/readwillbe.db
        -e READWILLBE_COOKIE_SECRET=dev-only-local-secret-min-32-chars
        -e READWILLBE_SEED_DB=true
        -e READWILLBE_ALLOW_SIGNUP=true
        -e READWILLBE_LOG_LEVEL=debug
        -e TEMPL_EXPERIMENT=rawgo
        -e READWILLBE_HOSTNAME=localhost:7331
        {{.DEV_IMAGE}}
        sh -c "bun install && /develop.sh"
    silent: true

  dev-stop:
    desc: Stop development environment
    cmds:
      - docker stop {{.APP_NAME}}-dev || true
      - task: clean:bun
      - rm -rf ./tmp ./bin
    silent: true

  build:
    desc: Build production Docker image
    cmds:
      - defer: rm ./readwillbe-dev.tar
      - dagger -m .dagger call release --source . --version dev-release export --path ./readwillbe-dev.tar
      - |
        id=$(docker load -i ./readwillbe-dev.tar | sed -n 's/^Loaded image.*: //p')
        docker tag $id {{.APP_NAME}}:latest

  fmt:
    desc: Auto-format go files
    cmds:
      - for file in $(gofmt -s -l . | grep -v "^vendor/"); do go fmt $file; done

  templ-fmt:
    desc: Auto-format templ files
    cmds:
      - for file in $(find ./views -type f -name '*.templ'); do templ fmt $file; done

  lint:
    desc: Run linter
    cmds:
      - dagger -m .dagger call lint --source=.

  test:
    desc: Run tests in Docker
    cmds:
      - dagger -m .dagger call test --source=.

  build-assets:
    desc: Compile CSS and React/TypeScript
    cmds:
      - dagger -m .dagger call build-assets --source=. export --path=./static

  typecheck:
    desc: Type-check TypeScript files
    cmds:
      - dagger -m .dagger call typecheck --source=.
